In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/nlp-getting-started/sample_submission.csv
/kaggle/input/nlp-getting-started/train.csv
/kaggle/input/nlp-getting-started/test.csv


In [2]:
train_data = pd.read_csv("/kaggle/input/nlp-getting-started/train.csv")
test_data = pd.read_csv("/kaggle/input/nlp-getting-started/test.csv")


In [3]:
train_data["text"].head()

0    Our Deeds are the Reason of this #earthquake M...
1               Forest fire near La Ronge Sask. Canada
2    All residents asked to 'shelter in place' are ...
3    13,000 people receive #wildfires evacuation or...
4    Just got sent this photo from Ruby #Alaska as ...
Name: text, dtype: object

In [4]:
from keras.preprocessing.text import Tokenizer
train_text_samples = train_data["text"]
test_text_samples = test_data["text"]

tokenizer = Tokenizer(num_words=1000);
tokenizer.fit_on_texts(train_text_samples)
tokenizer.fit_on_texts(test_text_samples)
train_text_sequences = tokenizer.texts_to_sequences(train_text_samples)
test_text_sequences = tokenizer.texts_to_sequences(test_text_samples)


one_hot_results = tokenizer.texts_to_matrix(train_text_samples, mode='binary')
word_index = tokenizer.word_index

print('Found %s unique tokens.' % len(word_index))
print(one_hot_results)

print(train_data.describe)


Found 29319 unique tokens.
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]]
<bound method NDFrame.describe of          id keyword location  \
0         1     NaN      NaN   
1         4     NaN      NaN   
2         5     NaN      NaN   
3         6     NaN      NaN   
4         7     NaN      NaN   
...     ...     ...      ...   
7608  10869     NaN      NaN   
7609  10870     NaN      NaN   
7610  10871     NaN      NaN   
7611  10872     NaN      NaN   
7612  10873     NaN      NaN   

                                                   text  target  
0     Our Deeds are the Reason of this #earthquake M...       1  
1                Forest fire near La Ronge Sask. Canada       1  
2     All residents asked to 'shelter in place' are ...       1  
3     13,000 people receive #wildfires evacuation or...       1  
4     Just got sent this photo from Ruby #Alaska as ...       1  
..

In [5]:
from keras.preprocessing.text import Tokenizer

samples = ['The cat sat on the mat.', 'The dog ate my homework.']

tokenizer = Tokenizer(num_words=1000);
tokenizer.fit_on_texts(samples)
sequences = tokenizer.texts_to_sequences(samples)

one_hot_results = tokenizer.texts_to_matrix(samples, mode='binary')
word_index = tokenizer.word_index

print('Found %s unique tokens.' % len(word_index))
print(one_hot_results)

Found 9 unique tokens.
[[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [6]:
from keras.datasets import imdb
from keras import preprocessing

max_features = 10000 #toplam yegane kelime sayısı
maxlen = 20 #yorumdan alınacak kelime sayısı

In [7]:
train_text_sequences = preprocessing.sequence.pad_sequences(train_text_sequences, maxlen=maxlen)
test_text_sequences = preprocessing.sequence.pad_sequences(test_text_sequences, maxlen=maxlen)

In [8]:
from keras.models import Sequential
from keras.layers import Flatten, Dense, Embedding

model = Sequential()

model.add(Embedding(10000, 8, input_length=maxlen))

model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 8)             80000     
_________________________________________________________________
flatten (Flatten)            (None, 160)               0         
_________________________________________________________________
dense (Dense)                (None, 1)                 161       
Total params: 80,161
Trainable params: 80,161
Non-trainable params: 0
_________________________________________________________________


In [9]:
history = model.fit(train_text_sequences, train_data["target"], epochs=10, batch_size=32, validation_split= 0.2)

Epoch 1/10
191/191 [==============================] - 0s 3ms/step - loss: 0.6639 - accuracy: 0.6115 - val_loss: 0.6351 - val_accuracy: 0.6592
Epoch 2/10
191/191 [==============================] - 0s 1ms/step - loss: 0.5989 - accuracy: 0.6992 - val_loss: 0.5801 - val_accuracy: 0.7223
Epoch 3/10
191/191 [==============================] - 0s 2ms/step - loss: 0.5375 - accuracy: 0.7488 - val_loss: 0.5391 - val_accuracy: 0.7531
Epoch 4/10
191/191 [==============================] - 0s 2ms/step - loss: 0.4899 - accuracy: 0.7785 - val_loss: 0.5139 - val_accuracy: 0.7597
Epoch 5/10
191/191 [==============================] - 0s 2ms/step - loss: 0.4577 - accuracy: 0.7998 - val_loss: 0.4966 - val_accuracy: 0.7735
Epoch 6/10
191/191 [==============================] - 0s 2ms/step - loss: 0.4343 - accuracy: 0.8130 - val_loss: 0.4831 - val_accuracy: 0.7800
Epoch 7/10
191/191 [==============================] - 0s 1ms/step - loss: 0.4166 - accuracy: 0.8199 - val_loss: 0.4740 - val_accuracy: 0.7807
Epoch 

In [10]:
model.predict(test_text_sequences)

array([[0.31201267],
       [0.46397793],
       [0.8716819 ],
       ...,
       [0.91487575],
       [0.8069712 ],
       [0.20928276]], dtype=float32)

In [11]:
def eitherZeroOne(arr):
    for predict in arr:
        if predict[0] < 0.50:
            predict[0] = int(0)
        else:
            predict[0] = int(1)
    return arr


In [12]:
submission_array = eitherZeroOne(model.predict(test_text_sequences))

In [13]:
submission_array = submission_array.reshape((3263))

In [14]:
submission_array_df = pd.DataFrame({'id': test_data["id"], 'target': submission_array.astype(int)})

In [15]:
submission_array_df.to_csv('output_submission.csv', index=False)